version: '3'

tasks:
  mongodb:
    desc: Start all mongodb containers
    aliases: [up]
    cmds:
      - docker compose up -d

  down:
    desc: Stop all mongodb containers
    cmds:
      - docker compose down

  logs:
    desc: Show mongodb logs
    cmds:
      - docker compose logs -f {{.CLI_ARGS}}

  ps:
    desc: Show mongodb container status
    cmds:
      - docker compose ps

  pull:
    desc: Pull latest mongodb images
    cmds:
      - docker compose pull

  restart:
    desc: Restart mongodb containers
    cmds:
      - docker compose restart
