version: '3'

tasks:
  portracker:
    desc: Start all portracker containers
    aliases: [up]
    cmds:
      - docker compose up -d

  down:
    desc: Stop all portracker containers
    cmds:
      - docker compose down

  logs:
    desc: Show portracker logs
    cmds:
      - docker compose logs -f {{.CLI_ARGS}}

  ps:
    desc: Show portracker container status
    cmds:
      - docker compose ps

  pull:
    desc: Pull latest portracker images
    cmds:
      - docker compose pull

  restart:
    desc: Restart portracker containers
    cmds:
      - docker compose restart
