services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    user: "1000:1000"
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      # - n8n_data:/home/node/.n8n
      - ./local_files:/files
    networks:
      - proxy-net
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost:5678/healthz || exit 1"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s
    restart: unless-stopped

# volumes:
#   n8n_data:

networks:
  proxy-net:
    external: true