services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - "8025:8025"
      - "1025:1025"
    env_file:
      - .env
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
