services:
  mysql:
    container_name: mysql_db
    build:
      context: ./docker
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/mysql
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init.sql:ro
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - proxy-net
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p\"$$MYSQL_ROOT_PASSWORD\" || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  proxy-net:
    external: true
