version: '3'

includes:
  homepage:
    taskfile: ./homepage
    dir: ./homepage
  adguard:
    taskfile: ./adguard
    dir: ./adguard
  portainer:
    taskfile: ./portainer
    dir: ./portainer
  dockge:
    taskfile: ./dockge
    dir: ./dockge
  portracker:
    taskfile: ./portracker
    dir: ./portracker
  npm:
    taskfile: ./npm
    dir: ./npm
  dozzle:
    taskfile: ./dozzle
    dir: ./dozzle

tasks:
  homepage:
    desc: Start homepage containers
    cmds:
      - task: homepage:homepage

  adguard:
    desc: Start adguard containers
    cmds:
      - task: adguard:adguard

  portainer:
    desc: Start portainer containers
    cmds:
      - task: portainer:portainer

  dockge:
    desc: Start dockge containers
    cmds:
      - task: dockge:dockge

  portracker:
    desc: Start portracker containers
    cmds:
      - task: portracker:portracker

  npm:
    desc: Start Nginx Proxy Manager containers
    cmds:
      - task: npm:npm

  dozzle:
    desc: Start dozzle containers
    cmds:
      - task: dozzle:dozzle

  up:
    desc: Start all enabled core containers
    cmds:
      - '[ ! -f adguard/.enabled ] || task adguard:up'
      - '[ ! -f npm/.enabled ] || task npm:up'
      - '[ ! -f portainer/.enabled ] || task portainer:up'
      - '[ ! -f dockge/.enabled ] || task dockge:up'
      - '[ ! -f portracker/.enabled ] || task portracker:up'
      - '[ ! -f dozzle/.enabled ] || task dozzle:up'
      - '[ ! -f homepage/.enabled ] || task homepage:up'

  down:
    desc: Stop all enabled core containers
    cmds:
      - '[ ! -f homepage/.enabled ] || task homepage:down'
      - '[ ! -f adguard/.enabled ] || task adguard:down'
      - '[ ! -f portainer/.enabled ] || task portainer:down'
      - '[ ! -f dockge/.enabled ] || task dockge:down'
      - '[ ! -f portracker/.enabled ] || task portracker:down'
      - '[ ! -f npm/.enabled ] || task npm:down'
      - '[ ! -f dozzle/.enabled ] || task dozzle:down'

  enable:
    desc: 'Enable a core service. Usage: task core:enable -- adguard'
    cmds:
      - touch {{.CLI_ARGS}}/.enabled
      - echo "Enabled {{.CLI_ARGS}}"

  disable:
    desc: 'Disable a core service. Usage: task core:disable -- adguard'
    cmds:
      - rm -f {{.CLI_ARGS}}/.enabled
      - echo "Disabled {{.CLI_ARGS}}"

  ps:
    desc: Show status of all core containers
    cmds:
      - task: homepage:ps
      - task: adguard:ps
      - task: portainer:ps
      - task: dockge:ps
      - task: portracker:ps
      - task: npm:ps
      - task: dozzle:ps

  pull:
    desc: Pull latest images for all core services
    cmds:
      - task: homepage:pull
      - task: adguard:pull
      - task: portainer:pull
      - task: dockge:pull
      - task: portracker:pull
      - task: npm:pull
      - task: dozzle:pull
