version: '3'

tasks:
  ollama:
    desc: Start all ollama containers
    aliases: [up]
    cmds:
      - docker compose up -d

  down:
    desc: Stop all ollama containers
    cmds:
      - docker compose down

  logs:
    desc: Show ollama logs
    cmds:
      - docker compose logs -f {{.CLI_ARGS}}

  ps:
    desc: Show ollama container status
    cmds:
      - docker compose ps

  pull:
    desc: Pull latest ollama images
    cmds:
      - docker compose pull

  restart:
    desc: Restart ollama containers
    cmds:
      - docker compose restart
