version: '3'

tasks:
  adguard:
    desc: Start all adguard containers
    aliases: [up]
    cmds:
      - docker compose up -d

  down:
    desc: Stop all adguard containers
    cmds:
      - docker compose down

  logs:
    desc: Show adguard logs
    cmds:
      - docker compose logs -f {{.CLI_ARGS}}

  ps:
    desc: Show adguard container status
    cmds:
      - docker compose ps

  pull:
    desc: Pull latest adguard images
    cmds:
      - docker compose pull

  restart:
    desc: Restart adguard containers
    cmds:
      - docker compose restart
