version: '3'

tasks:
  dockge:
    desc: Start all dockge containers
    aliases: [up]
    cmds:
      - docker compose up -d

  down:
    desc: Stop all dockge containers
    cmds:
      - docker compose down

  logs:
    desc: Show dockge logs
    cmds:
      - docker compose logs -f {{.CLI_ARGS}}

  ps:
    desc: Show dockge container status
    cmds:
      - docker compose ps

  pull:
    desc: Pull latest dockge images
    cmds:
      - docker compose pull

  restart:
    desc: Restart dockge containers
    cmds:
      - docker compose restart
