---
# For configuration options and examples, see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
    - GitHub:
        - abbr: GH
          href: https://github.com/
    - GitLab:
        - abbr: GL
          href: https://gitlab.com/
    - Stack Overflow:
        - abbr: SO
          href: https://stackoverflow.com/
    - MDN Web Docs:
        - abbr: MD
          href: https://developer.mozilla.org/
    - Docker Hub:
        - abbr: DH
          href: https://hub.docker.com/
    - npm:
        - abbr: np
          href: https://www.npmjs.com/

- Google:
    - Google:
        - abbr: GG
          href: https://www.google.com/
    - Mail:
        - abbr: GM
          href: https://mail.google.com/
    - Translate:
        - abbr: TR
          href: https://translate.google.com/
    - Gemini:
        - abbr: GM
          href: https://gemini.google.com/
    - Drive:
        - abbr: GD
          href: https://drive.google.com/
    - Calendar:
        - abbr: CA
          href: https://calendar.google.com/
    - Contacts:
        - abbr: CT
          href: https://contacts.google.com/
    - Youtube:
        - abbr: YT
          href: https://www.youtube.com/

- Social:
    - LinkedIn:
        - abbr: IN
          href: https://www.linkedin.com/
    - Facebook:
        - abbr: FB
          href: https://www.facebook.com/
    - Instagram:
        - abbr: IG
          href: https://www.instagram.com/
    - WhatsApp:
        - abbr: WA
          href: https://web.whatsapp.com/
    - Reddit:
        - abbr: RE
          href: https://www.reddit.com/
    - Twitter/X:
        - abbr: X
          href: https://x.com/

- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://www.youtube.com/
    - Netflix:
        - abbr: NF
          href: https://www.netflix.com/
    - Spotify:
        - abbr: SP
          href: https://open.spotify.com/
    - Twitch:
        - abbr: TW
          href: https://www.twitch.tv/
    - IMDb:
        - abbr: IM
          href: https://www.imdb.com/

- Communication:
    - Gmail:
        - abbr: GM
          href: https://mail.google.com/
    - Outlook:
        - abbr: OL
          href: https://outlook.live.com/
    - Discord:
        - abbr: DC
          href: https://discord.com/app/

- Productivity & Cloud:
    - Google Drive:
        - abbr: GD
          href: https://drive.google.com/
    - Notion:
        - abbr: NO
          href: https://www.notion.so/
    - Trello:
        - abbr: TR
          href: https://trello.com/

- Anime:
    - AnimeFLV:
        - abbr: AF
          href: https://www3.animeflv.net/
    - Crunchyroll:
        - abbr: CR
          href: https://www.crunchyroll.com/

- Comics:
    - Apoll Comics:
        - abbr: AP
          href: https://apollcomics.xyz/
    - Ver Man Hwa:
        - abbr: VM
          href: https://vermanhwa.com/

- Shopping & Services:
    - Mercado Libre:
        - abbr: ML
          href: https://www.mercadolibre.com.uy/
    - Amazon:
        - abbr: AM
          href: https://www.amazon.com/
    - eBay:
        - abbr: EB
          href: https://www.ebay.com/

- Banking:
    - Itaú:
        - abbr: IT
          href: https://www.itau.com.uy/
    - Scotiabank:
        - abbr: SC
          href: https://www.scotiabank.com.uy/