---
# For configuration options and examples, see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
    - GitHub:
        - icon: /icons/github.png
          abbr: GH
          href: https://github.com/
    - GitLab:
        - icon: /icons/gitlab.png
          abbr: GL
          href: https://gitlab.com/
    - Stack Overflow:
        - icon: /icons/stackoverflow.png
          abbr: SO
          href: https://stackoverflow.com/
    - MDN Web Docs:
        - icon: /icons/mdn.png
          abbr: MD
          href: https://developer.mozilla.org/
    - Docker Hub:
        - icon: /icons/dockerhub.png
          abbr: DH
          href: https://hub.docker.com/
    - npm:
        - icon: /icons/npm.png
          abbr: np
          href: https://www.npmjs.com/

- Google:
    - Google:
        - icon: /icons/google.png
          abbr: GG
          href: https://www.google.com/
    - Mail:
        - icon: mdi-email
          abbr: GM
          href: https://mail.google.com/
    - Translate:
        - icon: /icons/translate.png
          abbr: TR
          href: https://translate.google.com/
    - Gemini:
        - icon: /icons/gemini.png
          abbr: GM
          href: https://gemini.google.com/
    - Drive:
        - icon: /icons/googledrive.png
          abbr: GD
          href: https://drive.google.com/
    - Calendar:
        - icon: mdi-calendar
          abbr: CA
          href: https://calendar.google.com/
    - Contacts:
        - icon: mdi-account-group
          abbr: CT
          href: https://contacts.google.com/
    - Youtube:
        - icon: /icons/youtube.png
          abbr: YT
          href: https://www.youtube.com/

- Social:
    - LinkedIn:
        - icon: /icons/linkedin.png
          abbr: IN
          href: https://www.linkedin.com/
    - Facebook:
        - icon: /icons/facebook.png
          abbr: FB
          href: https://www.facebook.com/
    - Instagram:
        - icon: /icons/instagram.png
          abbr: IG
          href: https://www.instagram.com/
    - WhatsApp:
        - icon: /icons/whatsapp.png
          abbr: WA
          href: https://web.whatsapp.com/
    - Reddit:
        - icon: /icons/reddit.png
          abbr: RE
          href: https://www.reddit.com/
    - Twitter/X:
        - icon: /icons/x.png
          abbr: X
          href: https://x.com/

- Entertainment:
    - YouTube:
        - icon: /icons/youtube.png
          abbr: YT
          href: https://www.youtube.com/
    - Netflix:
        - icon: /icons/netflix.png
          abbr: NF
          href: https://www.netflix.com/
    - Spotify:
        - icon: /icons/spotify.png
          abbr: SP
          href: https://open.spotify.com/
    - Twitch:
        - icon: /icons/twitch.png
          abbr: TW
          href: https://www.twitch.tv/
    - IMDb:
        - icon: /icons/imdb.png
          abbr: IM
          href: https://www.imdb.com/

- Communication:
    - Gmail:
        - icon: mdi-email
          abbr: GM
          href: https://mail.google.com/
    - Outlook:
        - icon: /icons/outlook.png
          abbr: OL
          href: https://outlook.live.com/
    - Discord:
        - icon: /icons/discord.png
          abbr: DC
          href: https://discord.com/app/

- Productivity & Cloud:
    - Google Drive:
        - icon: mdi-google-drive
          abbr: GD
          href: https://drive.google.com/
    - Notion:
        - icon: /icons/notion.png
          abbr: NO
          href: https://www.notion.so/
    - Trello:
        - icon: /icons/trello.png
          abbr: TR
          href: https://trello.com/

- Anime:
    - AnimeFLV:
        - icon: /icons/animeflv.png
          abbr: AF
          href: https://www3.animeflv.net/
    - Crunchyroll:
        - icon: /icons/crunchyroll.png
          abbr: CR
          href: https://www.crunchyroll.com/

- Comics:
    - Apoll Comics:
        - icon: /icons/apollcomics.png
          abbr: AP
          href: https://apollcomics.xyz/
    - Ver Manhwa:
        - icon: /icons/vermanhwa.png
          abbr: VM
          href: https://vermanhwa.com/
    - M440:
        - icon: /icons/m440.png
          abbr: M4
          href: https://m440.in/

- Shopping & Services:
    - Mercado Libre:
        - icon: /icons/mercadolibre.png
          abbr: ML
          href: https://www.mercadolibre.com.uy/
    - Amazon:
        - icon: /icons/amazon.png
          abbr: AM
          href: https://www.amazon.com/
    - eBay:
        - icon: /icons/ebay.png
          abbr: EB
          href: https://www.ebay.com/

- Banking:
    - Itaú:
        - icon: /icons/itau.png
          abbr: IT
          href: https://www.itau.com.uy/
    - Scotiabank:
        - icon: /icons/scotiabank.png
          abbr: SC
          href: https://www.scotiabank.com.uy/