---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Homepage

background: 
  image: /images/background-1.jpg
  blur: xs
  saturate: 50
  brightness: 50
  opacity: 50

blockHighlights:
  levels:
    good: "bg-emerald-500/40 text-emerald-950 dark:bg-emerald-900/60 dark:text-emerald-400"
    warn: "bg-amber-300/30 text-amber-900 dark:bg-amber-900/30 dark:text-amber-200"
    danger: "bg-rose-700/45 text-rose-200 dark:bg-rose-950/70 dark:text-rose-400"

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
