---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    cputemp: true
    memory: true
    disk: /
    network: true
    # uptime: true
    weather: true

- search:
    provider: duckduckgo
    target: _blank

# - openmeteo:
#     label: Montevideo
#     latitude: 34.9055
#     longitude: 56.1851
#     timezone: America/Montevideo
#     units: metric
#     cache: 5