---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    label: System
    cpu: true
    cputemp: true
    memory: true
    network: true
    uptime: true
    weather: true

- resources:
    label: Storage
    disk:
      - /
      - /mnt/data

- search:
    provider: duckduckgo
    target: _blank

# - openmeteo:
#     label: Montevideo
#     latitude: 34.9055
#     longitude: 56.1851
#     timezone: America/Montevideo
#     units: metric
#     cache: 5
